server:
  port: 8080

  spring:
    datasource:
      password:
        url: jdbc:mysql://localhost:3306/admin-db
        username: root
        password: root
      application:
        name: spring-admin-app